### ISSUE TITLE
Project not found

### ISSUE THREAD

**Issue by leo-regov** [technote-space/auto-card-labeler#254]
As like the title says, on project_card.moved, I'm getting 
![image](https://user-images.githubusercontent.com/66946660/148723413-2be65174-90e3-4b88-b5e6-5ccd26d3d88a.png)

Configuration file follows what has been set in the README.

.github/card-labeler.yml -> THIS DOES NOT WORK
```
Project TestProject: 
  Column Todo:
    - 'To do'
  Column Reopened:
    - 'Reopened'
  Column Testing:
    - 'Testing'
  Column Ready to merge:
    - 'Ready to merge'
  Column Done:
    - 'Done'
```

.github/card-labeler-v2.yml -> THIS DOES NOT WORK
```
Project 1: # This should reflect
  Column Todo:
    - 'To do'
  Column Reopened:
    - 'Reopened'
  Column Testing:
    - 'Testing'
  Column Ready to merge:
    - 'Ready to merge'
  Column Done:
    - 'Done'
 ```

The action.yml
```
name: Auto labeler

on:
  project_card:
    types: [ moved ]

jobs:
  labeling:
    name: Card Labeler
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/auto-card-labeler@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GIT_API_KEY }}
          CONFIG_FILENAME: card-labeler-v2.yml
```
